"""
Student information for this assignment:

Replace <FULL NAME> with your name.
On my/our honor, Dillan Hong, this
programming assignment is my own work and I have not provided this code to
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1: dmh4484
"""


def length_of_longest_substring_n3(s):
    """
    Finds the length of the longest substring without repeating characters
    using a brute force approach (O(N^3)).

    pre: s is a string of arbitrary length, possibly empty.
    post: Returns an integer >= 0 representing the length of the longest substring
          in s that contains no repeating characters.
    """
    max_len = 0
    for i in range(len(s)):
        for j in range(i, len(s)):
            lst = [0] * 256
            no_repeat = True
            for char in range(i, j + 1):
                char_id = ord(s[char])
                lst[char_id] += 1
                if lst[char_id] > 1:
                    no_repeat = False
                    break

            if no_repeat:
                max_len = max(max_len, j - i + 1)

    return max_len


def length_of_longest_substring_n2(s):
    """
    Finds the length of the longest substring without repeating characters
    using a frequency list approach (O(N^2)), converting each character to
    their corresponding numeric representation in ASCII as the index into the
    frequency list.

    pre: s is a string of arbitrary length, possibly empty.
    post: Returns an integer >= 0 representing the length of the longest substring
          in s that contains no repeating characters.
    """
    # repeat format similar to last function
    max_len = 0
    for i in range(len(s)):
        lst = [0] * 256
        current_length = 0
        for j in range(i, len(s)):
            char_id = ord(s[j])
            lst[char_id] += 1
            if lst[char_id] > 1:
                break
            current_length += 1
            max_len = max(max_len, current_length)

    return max_len


def length_of_longest_substring_n(s):
    """
    Finds the length of the longest substring without repeating characters
    using a frequency list approach (O(N)), converting each character to
    their corresponding numeric representation in ASCII as the index into the
    frequency list. However, this approach stops early, breaking out of the inner
    loop when a repeating character is found. You may also choose to challenge
    yourself by implementing a sliding window approach.

    pre: s is a string of arbitrary length, possibly empty.
    post: Returns an integer >= 0 representing the length of the longest substring
          in s that contains no repeating characters.
    """
    # create window for sliding window method
    # increment right to expand window, increment left forward if duplicates
    # create a loop for right boundary
    # create while loop for duplicates, shrink window
    max_len = 0
    lst = [0] * 256
    left = 0
    n = len(s)
    for right in range(n):
        char_id = ord(s[right])
        lst[char_id] += 1

        while lst[char_id] > 1:
            lst[ord(s[left])] -= 1
            left += 1

        max_len = max(max_len, right - left + 1)

    return max_len
